### ISSUE TITLE
ecmascript should be included as dependency?

### ISSUE THREAD

**Issue by screaser** [vazco/universe-mailchimp-v3-api#1]
If you add this package to an older Meteor project, when running you get an error message like:

 (function(Npm,Assets){(function(){import mailchimpAPI from 'meteor/universe:mailchimp-v3-api';
                                                             ^^^^^^
Unexpected reserved word (import)

It turns out that you need to include the ecmascript module for it to work. Apparently this is a part of newer Meteor projects automatically; but if you are updating an old one you need to manually add it:

meteor add ecmascript

To avoid having that cryptic message happen to some folks working on older code, perhaps ecmascript should be added as a dependency to universe-mailchimp-v3-api?

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
